# This file was generated by GoReleaser. DO NOT EDIT.
cask "omakase" do
  version "0.31.0"

  on_macos do
    on_intel do
      sha256 "e853be8ad6a927e0c3c536b4022a93ed88f5b1eee1a267a65ab35661b927082a"
      url "https://github.com/Yuncun/omakase-harness/releases/download/v#{version}/omakase_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0cde282a57516f2a2628a8e667a7d768de16bb4d6c991e99e132e8c5177e1fe4"
      url "https://github.com/Yuncun/omakase-harness/releases/download/v#{version}/omakase_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "41abbbe0b7c264593b991782ed10911a3c8b5cc64edad63f1553a0e8287e96ee"
      url "https://github.com/Yuncun/omakase-harness/releases/download/v#{version}/omakase_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8e9a02e76d2d6989fbb04d3cc8b362b15d8e7d5d8a18453619be04a463b2bd28"
      url "https://github.com/Yuncun/omakase-harness/releases/download/v#{version}/omakase_#{version}_linux_arm64.tar.gz"
    end
  end

  name "omakase"
  desc "Install a repo's local dev harness as a gitignored overlay"
  homepage "https://github.com/Yuncun/omakase-harness"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omakase"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/omakase"]
    end
  end

  # No zap stanza required

end
