# This file was generated by GoReleaser. DO NOT EDIT.
cask "omakase" do
  version "0.28.0"

  on_macos do
    on_intel do
      sha256 "90a8a20892dc3e6807ad7e22770b511c6fc5d485e5a037d4b1886f279d035920"
      url "https://github.com/Yuncun/omakase-harness/releases/download/v#{version}/omakase_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "339f66b10ded1ee10f1db352cd0ad0ac4dc3dfedab0619566dad508bd3bea6b0"
      url "https://github.com/Yuncun/omakase-harness/releases/download/v#{version}/omakase_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ec2ca8200968757209ce78e944ea0c670824df694db7a371440de2ba546375b"
      url "https://github.com/Yuncun/omakase-harness/releases/download/v#{version}/omakase_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "097aad25d74eb8188a2ad54fca308ba7c66a2a76f8a5aa992637af07e09137d7"
      url "https://github.com/Yuncun/omakase-harness/releases/download/v#{version}/omakase_#{version}_linux_arm64.tar.gz"
    end
  end

  name "omakase"
  desc "Install a repo's local dev harness as a gitignored overlay"
  homepage "https://github.com/Yuncun/omakase-harness"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omakase"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/omakase"]
    end
  end

  # No zap stanza required

end
