# This file was generated by GoReleaser. DO NOT EDIT.
cask "omakase" do
  version "0.29.0"

  on_macos do
    on_intel do
      sha256 "d07bc825247d6d3e3eaaceb7622474933e7d946584bb0bf9c097f4dff5af352d"
      url "https://github.com/Yuncun/omakase-harness/releases/download/v#{version}/omakase_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "09087861eb6298e3230e8e1b3944a8e7e70cf540963d10c3d55f3267a61b8b96"
      url "https://github.com/Yuncun/omakase-harness/releases/download/v#{version}/omakase_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd598012cc755b700a63d038b2740c3d7207e47929c36a7343263f2f501e3641"
      url "https://github.com/Yuncun/omakase-harness/releases/download/v#{version}/omakase_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b839026c4a2a658ba5d5566322895d6c271866893738fa73bc3eec4fc148e83d"
      url "https://github.com/Yuncun/omakase-harness/releases/download/v#{version}/omakase_#{version}_linux_arm64.tar.gz"
    end
  end

  name "omakase"
  desc "Install a repo's local dev harness as a gitignored overlay"
  homepage "https://github.com/Yuncun/omakase-harness"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omakase"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/omakase"]
    end
  end

  # No zap stanza required

end
